'use client';
import { useEffect, useState } from 'react';
import { supabaseBrowser } from '../lib/supabase';

type Listing={id:string;title:string;description:string;food_type:string;quantity:string;country:string;city:string;pickup_start:string;pickup_end:string;status:string;donor_id:string};
const foods=['All','Prepared meals','Bakery','Produce','Groceries','Other'];

export default function Home(){
 const [items,setItems]=useState<Listing[]>([]); const [q,setQ]=useState(''); const [food,setFood]=useState('All'); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [auth,setAuth]=useState(false); const [show,setShow]=useState<'login'|'list'|'claim'|null>(null); const [selected,setSelected]=useState<Listing|null>(null);
 const sb=supabaseBrowser();
 async function load(){setLoading(true); const {data,error}=await sb.from('food_listings').select('*').in('status',['available','reserved']).order('pickup_start',{ascending:true}); if(error)setError(error.message); else setItems((data||[]) as Listing[]); setLoading(false);}
 useEffect(()=>{load(); sb.auth.getUser().then(({data})=>setAuth(!!data.user));},[]);
 const filtered=items.filter(x=>(food==='All'||x.food_type===food)&&`${x.title} ${x.city} ${x.country} ${x.description}`.toLowerCase().includes(q.toLowerCase()));
 function openClaim(x:Listing){if(!auth){setShow('login');return} setSelected(x);setShow('claim')}
 return <main><nav className="nav shell"><div className="brand">FoodLoop<span/></div><div className="navlinks"><a className="btn alt hide" href="#discover">Discover</a>{auth?<button className="btn" onClick={()=>setShow('list')}>Give food</button>:<button className="btn" onClick={()=>setShow('login')}>Sign in</button>}</div></nav>
 <section className="hero shell"><div><div className="eyebrow">A global food rescue network</div><h1>Good food deserves another chance.</h1><p>FoodLoop connects surplus food from restaurants, shops and households with people and community groups who can use it — before it goes to waste.</p></div><div className="heroCard"><small>THE IDEA</small><div className="big">Share more.<br/>Waste less.</div><small>Start locally. Make an impact anywhere.</small></div></section>
 <section id="discover" className="section shell"><div className="searchbar"><input aria-label="Search food" placeholder="Search food, city or country…" value={q} onChange={e=>setQ(e.target.value)}/><select value={food} onChange={e=>setFood(e.target.value)} aria-label="Food type">{foods.map(f=><option key={f}>{f}</option>)}</select></div>
 {error&&<div className="error">{error} Check your Supabase environment variables and database setup.</div>}
 {loading?<div className="empty">Loading available food…</div>:<div className="grid">{filtered.length?filtered.map(x=><article className="card" key={x.id}><span className="pill">{x.food_type}</span><h3>{x.title}</h3><div className="meta">{x.quantity}<br/>{x.city}, {x.country}<br/>Pickup {new Date(x.pickup_start).toLocaleString([], {dateStyle:'medium',timeStyle:'short'})} — {new Date(x.pickup_end).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}</div><div className="bottom"><span className="meta">{x.status==='available'?'Available now':'Reserved'}</span><button className="btn" disabled={x.status!=='available'} onClick={()=>openClaim(x)}>{x.status==='available'?'Request':'Reserved'}</button></div></article>):<div className="empty"><strong>No active food listings yet.</strong><br/>When donors post real surplus food, it will appear here. No fake listings.</div>}</div>}</section>
 <footer className="footer shell"><div>FoodLoop © {new Date().getFullYear()}</div><div>Created by <strong>Koglesh R. Murugan</strong></div></footer>
 {show==='login'&&<Auth close={()=>setShow(null)} onDone={()=>{setAuth(true);setShow(null)}}/>}{show==='list'&&<ListingForm close={()=>setShow(null)} done={()=>{setShow(null);load()}}/>}{show==='claim'&&selected&&<Claim listing={selected} close={()=>setShow(null)} done={()=>{setShow(null);load()}}/>}</main>
}
function Auth({close,onDone}:{close:()=>void;onDone:()=>void}){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [name,setName]=useState('');const [signup,setSignup]=useState(false);const [err,setErr]=useState('');const sb=supabaseBrowser();async function go(){setErr('');const r=signup?await sb.auth.signUp({email,password,options:{data:{display_name:name}}}):await sb.auth.signInWithPassword({email,password});if(r.error)setErr(r.error.message);else onDone()}return <div className="modal"><div className="modalbox"><button onClick={close} style={{float:'right',border:0,background:'none'}}>✕</button><div className="eyebrow">FoodLoop account</div><h2>{signup?'Join FoodLoop':'Welcome back'}</h2><div className="form">{signup&&<input placeholder="Your name" value={name} onChange={e=>setName(e.target.value)}/>}<input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/>{err&&<div className="error">{err}</div>}<button className="btn" onClick={go}>{signup?'Create account':'Sign in'}</button><button className="btn alt" onClick={()=>setSignup(!signup)}>{signup?'Already have an account':'Create an account'}</button></div></div></div>}
function ListingForm({close,done}:{close:()=>void;done:()=>void}){const [f,setF]=useState({title:'',description:'',food_type:'Prepared meals',quantity:'',country:'',city:'',address:'',start:'',end:''});const [err,setErr]=useState('');const sb=supabaseBrowser();const set=(k:string,v:string)=>setF({...f,[k]:v});async function save(){setErr('');const {data:{user}}=await sb.auth.getUser();if(!user){setErr('Please sign in.');return}if(!f.title||!f.quantity||!f.country||!f.city||!f.address||!f.start||!f.end){setErr('Please complete all required fields.');return}const {error}=await sb.from('food_listings').insert({donor_id:user.id,title:f.title,description:f.description,food_type:f.food_type,quantity:f.quantity,country:f.country,city:f.city,pickup_address:f.address,pickup_start:new Date(f.start).toISOString(),pickup_end:new Date(f.end).toISOString()});if(error)setErr(error.message);else done()}return <div className="modal"><div className="modalbox"><button onClick={close} style={{float:'right',border:0,background:'none'}}>✕</button><div className="eyebrow">Give surplus food</div><h2>Post a rescue</h2><div className="form"><input placeholder="What food is available? *" value={f.title} onChange={e=>set('title',e.target.value)}/><textarea placeholder="Short description" value={f.description} onChange={e=>set('description',e.target.value)}/><div className="row"><select value={f.food_type} onChange={e=>set('food_type',e.target.value)}>{foods.slice(1).map(x=><option key={x}>{x}</option>)}</select><input placeholder="Quantity (e.g. 20 meals) *" value={f.quantity} onChange={e=>set('quantity',e.target.value)}/></div><div className="row"><input placeholder="Country *" value={f.country} onChange={e=>set('country',e.target.value)}/><input placeholder="City *" value={f.city} onChange={e=>set('city',e.target.value)}/></div><input placeholder="Pickup location/address *" value={f.address} onChange={e=>set('address',e.target.value)}/><div className="row"><input type="datetime-local" value={f.start} onChange={e=>set('start',e.target.value)}/><input type="datetime-local" value={f.end} onChange={e=>set('end',e.target.value)}/></div><div className="notice">Only share a pickup location you are comfortable making available to a requester.</div>{err&&<div className="error">{err}</div>}<button className="btn" onClick={save}>Publish real listing</button></div></div></div>}
function Claim({listing,close,done}:{listing:Listing;close:()=>void;done:()=>void}){const [msg,setMsg]=useState('');const [err,setErr]=useState('');const sb=supabaseBrowser();async function send(){const {data:{user}}=await sb.auth.getUser();if(!user)return setErr('Please sign in.');const {error}=await sb.from('food_claims').insert({listing_id:listing.id,claimant_id:user.id,message:msg});if(error)setErr(error.message);else done()}return <div className="modal"><div className="modalbox"><button onClick={close} style={{float:'right',border:0,background:'none'}}>✕</button><div className="eyebrow">Request food</div><h2>{listing.title}</h2><p className="meta">{listing.quantity} · {listing.city}, {listing.country}</p><div className="form"><textarea placeholder="Optional note to the donor" value={msg} onChange={e=>setMsg(e.target.value)}/><div className="notice">Requesting food does not guarantee it. The donor decides who can collect it.</div>{err&&<div className="error">{err}</div>}<button className="btn" onClick={send}>Send request</button></div></div></div>}
